//! Web dashboard generator for ESPHome REST API.
//!
//! Generates a complete web interface (HTML + JS/TS) from discovered entities.

use crate::entities::RestEndpoint;
use std::fs;
use std::path::Path;

/// Generate the web dashboard files in the specified directory.
pub fn generate(
    host: &str,
    device_name: &str,
    endpoints: &[RestEndpoint],
    out_dir: &str,
    lang: &str, // "js" or "ts"
) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(out_dir)?;

    // Write api.js or api.ts
    let api_code = generate_api_code(host, lang);
    let api_path = Path::new(out_dir).join(format!("api.{}", lang));
    fs::write(&api_path, api_code)?;

    // Write index.html
    let html = generate_html(host, device_name, endpoints);
    let html_path = Path::new(out_dir).join("index.html");
    fs::write(&html_path, html)?;

    // Write tsconfig.json for TypeScript
    if lang == "ts" {
        let tsconfig = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "./dist",
    "rootDir": ".",
    "declaration": true,
    "sourceMap": true
  },
  "include": ["*.ts"],
  "exclude": ["node_modules"]
}
"#;
        fs::write(Path::new(out_dir).join("tsconfig.json"), tsconfig)?;
    }

    // Write package.json
    let pkg = if lang == "ts" {
        format!(
            r#"{{
  "name": "esphome-dashboard",
  "version": "1.0.0",
  "description": "ESPHome REST Dashboard for {}",
  "scripts": {{
    "build": "tsc && node -e \"require('fs').cpSync('index.html','dist/index.html')\"",
    "serve": "npm run build && python -m http.server 8080 --directory dist"
  }},
  "devDependencies": {{
    "typescript": "^5.0.0"
  }}
}}
"#,
            device_name
        )
    } else {
        format!(
            r#"{{
  "name": "esphome-dashboard",
  "version": "1.0.0",
  "description": "ESPHome REST Dashboard for {}",
  "scripts": {{
    "build": "echo No build needed",
    "serve": "python -m http.server 8080"
  }}
}}
"#,
            device_name
        )
    };
    fs::write(Path::new(out_dir).join("package.json"), pkg)?;

    let abs_path = fs::canonicalize(out_dir).unwrap_or_else(|_| Path::new(out_dir).to_path_buf());
    println!("\nWeb interface generated in: {}", abs_path.display());
    println!("  - index.html");
    println!("  - api.{}", lang);
    println!("  - package.json");
    if lang == "ts" {
        println!("  - tsconfig.json");
    }
    println!("\nOpen index.html in a browser to use the dashboard.");

    Ok(())
}

fn generate_api_code(host: &str, lang: &str) -> String {
    if lang == "ts" {
        format!(
            r#"// ESPHome REST API Client - TypeScript
// Auto-generated by get_ids

const BASE_URL = 'http://{}';

interface EntityState {{
  id: string;
  state: string;
  value: string | number | boolean;
  [key: string]: unknown;
}}

async function getEntity(endpoint: string): Promise<EntityState> {{
  const resp = await fetch(`${{BASE_URL}}${{endpoint}}`);
  if (!resp.ok) throw new Error(`GET ${{endpoint}} failed: ${{resp.status}}`);
  return resp.json();
}}

async function postAction(endpoint: string, action: string): Promise<Response> {{
  const resp = await fetch(`${{BASE_URL}}${{endpoint}}/${{action}}`, {{ method: 'POST' }});
  if (!resp.ok) throw new Error(`POST ${{endpoint}}/${{action}} failed: ${{resp.status}}`);
  return resp;
}}

async function postValue(endpoint: string, value: string | number): Promise<Response> {{
  const url = `${{BASE_URL}}${{endpoint}}/set?value=${{encodeURIComponent(String(value))}}`;
  const resp = await fetch(url, {{ method: 'POST' }});
  if (!resp.ok) throw new Error(`POST set value failed: ${{resp.status}}`);
  return resp;
}}

async function postTime(endpoint: string, hour: number, minute: number, second: number): Promise<Response> {{
  const url = `${{BASE_URL}}${{endpoint}}/set?hour=${{hour}}&minute=${{minute}}&second=${{second}}`;
  const resp = await fetch(url, {{ method: 'POST' }});
  if (!resp.ok) throw new Error(`POST set time failed: ${{resp.status}}`);
  return resp;
}}
"#,
            host
        )
    } else {
        format!(
            r#"// ESPHome REST API Client - JavaScript
// Auto-generated by get_ids

const BASE_URL = 'http://{}';

async function getEntity(endpoint) {{
  const resp = await fetch(`${{BASE_URL}}${{endpoint}}`);
  if (!resp.ok) throw new Error(`GET ${{endpoint}} failed: ${{resp.status}}`);
  return resp.json();
}}

async function postAction(endpoint, action) {{
  const resp = await fetch(`${{BASE_URL}}${{endpoint}}/${{action}}`, {{ method: 'POST' }});
  if (!resp.ok) throw new Error(`POST ${{endpoint}}/${{action}} failed: ${{resp.status}}`);
  return resp;
}}

async function postValue(endpoint, value) {{
  const url = `${{BASE_URL}}${{endpoint}}/set?value=${{encodeURIComponent(String(value))}}`;
  const resp = await fetch(url, {{ method: 'POST' }});
  if (!resp.ok) throw new Error(`POST set value failed: ${{resp.status}}`);
  return resp;
}}

async function postTime(endpoint, hour, minute, second) {{
  const url = `${{BASE_URL}}${{endpoint}}/set?hour=${{hour}}&minute=${{minute}}&second=${{second}}`;
  const resp = await fetch(url, {{ method: 'POST' }});
  if (!resp.ok) throw new Error(`POST set time failed: ${{resp.status}}`);
  return resp;
}}
"#,
            host
        )
    }
}

fn entity_icon(entity_type: &str) -> &'static str {
    match entity_type {
        "Binary Sensor" => "&#x1f534;",
        "Sensor" => "&#x1f4ca;",
        "Text Sensor" => "&#x1f4dd;",
        "Switch" => "&#x1f50c;",
        "Button" => "&#x1f518;",
        "Light" => "&#x1f4a1;",
        "Fan" => "&#x1f32c;",
        "Cover" => "&#x1f3e0;",
        "Climate" => "&#x1f321;",
        "Number" => "&#x1f522;",
        "Select" => "&#x1f4cb;",
        "Lock" => "&#x1f512;",
        "Time" => "&#x1f552;",
        "Text" => "&#x1f4ac;",
        _ => "&#x2699;",
    }
}

fn entity_card_html(ep: &RestEndpoint) -> String {
    let oid = &ep.object_id;
    let name = html_escape(&ep.entity_name);
    let endpoint = &ep.endpoint;
    let etype = ep.ep_type.as_str();

    let mut card = String::new();
    card.push_str(&format!(
        "        <div class=\"card\" id=\"card-{}\">\n",
        oid
    ));
    card.push_str(&format!(
        "          <h3><span class=\"status-dot\"></span>{}</h3>\n",
        name
    ));
    card.push_str(&format!(
        "          <div class=\"endpoint\">{}</div>\n",
        endpoint
    ));
    card.push_str("          <div class=\"state\">--</div>\n");

    match etype {
        "Switch" | "Light" | "Fan" => {
            card.push_str("          <div class=\"actions\">\n");
            card.push_str(&format!("            <button class=\"on\" onclick=\"doAction('{}','turn_on','{}')\">ON</button>\n", endpoint, oid));
            card.push_str(&format!("            <button class=\"off\" onclick=\"doAction('{}','turn_off','{}')\">OFF</button>\n", endpoint, oid));
            card.push_str(&format!("            <button onclick=\"doAction('{}','toggle','{}')\">Toggle</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Button" => {
            card.push_str("          <div class=\"actions\">\n");
            card.push_str(&format!("            <button class=\"press\" onclick=\"doAction('{}','press','{}')\">Press</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Cover" => {
            card.push_str("          <div class=\"actions\">\n");
            card.push_str(&format!("            <button onclick=\"doAction('{}','open','{}')\">Open</button>\n", endpoint, oid));
            card.push_str(&format!("            <button onclick=\"doAction('{}','close','{}')\">Close</button>\n", endpoint, oid));
            card.push_str(&format!("            <button onclick=\"doAction('{}','stop','{}')\">Stop</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Lock" => {
            card.push_str("          <div class=\"actions\">\n");
            card.push_str(&format!("            <button class=\"on\" onclick=\"doAction('{}','lock','{}')\">Lock</button>\n", endpoint, oid));
            card.push_str(&format!("            <button class=\"off\" onclick=\"doAction('{}','unlock','{}')\">Unlock</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Number" => {
            card.push_str("          <div class=\"input-row\">\n");
            card.push_str(&format!("            <input type=\"number\" id=\"input-{}\" step=\"any\" />\n", oid));
            card.push_str(&format!("            <button onclick=\"doSetValue('{}','{}')\">Set</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Select" => {
            card.push_str("          <div class=\"input-row\">\n");
            card.push_str(&format!("            <select id=\"input-{}\" style=\"width:140px;\">\n", oid));
            for opt in &ep.options {
                let escaped_opt = html_escape(opt);
                card.push_str(&format!("              <option value=\"{}\">{}</option>\n", escaped_opt, escaped_opt));
            }
            card.push_str("            </select>\n");
            card.push_str(&format!("            <button onclick=\"doSetOption('{}','{}')\">Set</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Time" => {
            card.push_str("          <div class=\"input-row\">\n");
            card.push_str(&format!(
                "            <input type=\"time\" id=\"input-{}\" step=\"1\" />\n",
                oid
            ));
            card.push_str(&format!(
                "            <button onclick=\"doSetTime('{}','{}')\">Set</button>\n",
                endpoint, oid
            ));
            card.push_str("          </div>\n");
        }
        "Text" => {
            card.push_str("          <div class=\"input-row\">\n");
            card.push_str(&format!("            <input type=\"text\" id=\"input-{}\" placeholder=\"text\" style=\"width:160px;\" />\n", oid));
            card.push_str(&format!("            <button onclick=\"doSetValue('{}','{}')\">Set</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        "Climate" => {
            card.push_str("          <div class=\"input-row\">\n");
            card.push_str(&format!("            <input type=\"number\" id=\"input-{}\" step=\"0.5\" placeholder=\"temp\" />\n", oid));
            card.push_str(&format!("            <button onclick=\"doSetValue('{}','{}')\">Set</button>\n", endpoint, oid));
            card.push_str("          </div>\n");
        }
        _ => {}
    }

    card.push_str("        </div>\n");
    card
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn generate_entities_json(endpoints: &[RestEndpoint]) -> String {
    let mut json = String::from("[");
    for (i, ep) in endpoints.iter().enumerate() {
        if i > 0 {
            json.push(',');
        }
        let methods: Vec<String> = ep.methods.iter().map(|m| format!("\"{}\"", m)).collect();
        let actions: Vec<String> = ep.actions.iter().map(|a| format!("\"{}\"", json_escape(a))).collect();
        let options_json = if !ep.options.is_empty() {
            let opts: Vec<String> = ep.options.iter().map(|o| format!("\"{}\"" , json_escape(o))).collect();
            format!(",\"options\":[{}]", opts.join(","))
        } else {
            String::new()
        };
        json.push_str(&format!(
            r#"{{"type":"{}","entity":"{}","object_id":"{}","methods":[{}],"endpoint":"{}","actions":[{}]{}}}"#,
            json_escape(&ep.ep_type),
            json_escape(&ep.entity_name),
            json_escape(&ep.object_id),
            methods.join(","),
            json_escape(&ep.endpoint),
            actions.join(","),
            options_json
        ));
    }
    json.push(']');
    json
}

fn generate_html(host: &str, device_name: &str, endpoints: &[RestEndpoint]) -> String {
    let type_order = [
        "Binary Sensor",
        "Sensor",
        "Text Sensor",
        "Switch",
        "Button",
        "Light",
        "Fan",
        "Cover",
        "Climate",
        "Number",
        "Select",
        "Lock",
        "Time",
        "Text",
    ];

    // Group endpoints by type
    let mut groups: std::collections::BTreeMap<String, Vec<&RestEndpoint>> =
        std::collections::BTreeMap::new();
    for ep in endpoints {
        groups.entry(ep.ep_type.clone()).or_default().push(ep);
    }

    // Build sections HTML
    let mut sections = String::new();
    for t in &type_order {
        if let Some(eps) = groups.get(*t) {
            let mut sorted = eps.clone();
            sorted.sort_by(|a, b| a.entity_name.cmp(&b.entity_name));
            let icon = entity_icon(t);
            sections.push_str(&format!("    <div class=\"section\">\n"));
            sections.push_str(&format!(
                "      <h2>{} {} ({})</h2>\n",
                icon,
                t,
                sorted.len()
            ));
            sections.push_str("      <div class=\"cards\">\n");
            for ep in &sorted {
                sections.push_str(&entity_card_html(ep));
            }
            sections.push_str("      </div>\n");
            sections.push_str("    </div>\n");
        }
    }

    let entities_json = generate_entities_json(endpoints);
    let escaped_name = html_escape(device_name);

    format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{name} - ESPHome Dashboard</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
           background: #0d1117; color: #c9d1d9; padding: 20px; }}
    h1 {{ text-align: center; color: #58a6ff; margin-bottom: 8px; font-size: 1.8em; }}
    .subtitle {{ text-align: center; color: #8b949e; margin-bottom: 24px; font-size: 0.9em; }}
    .section {{ margin-bottom: 24px; }}
    .section h2 {{ color: #58a6ff; border-bottom: 1px solid #21262d; padding-bottom: 8px;
                   margin-bottom: 12px; font-size: 1.2em; }}
    .cards {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 12px; }}
    .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; }}
    .card h3 {{ font-size: 0.95em; color: #e6edf3; margin-bottom: 8px; }}
    .card .endpoint {{ font-size: 0.75em; color: #8b949e; margin-bottom: 8px; font-family: monospace; }}
    .card .state {{ font-size: 1.3em; font-weight: 600; color: #58a6ff; margin-bottom: 8px;
                    min-height: 1.5em; }}
    .card .state.on {{ color: #3fb950; }}
    .card .state.off {{ color: #f85149; }}
    .card .actions {{ display: flex; gap: 6px; flex-wrap: wrap; }}
    .card .actions button {{ background: #21262d; color: #c9d1d9; border: 1px solid #30363d;
                             border-radius: 4px; padding: 4px 12px; cursor: pointer; font-size: 0.8em; }}
    .card .actions button:hover {{ background: #30363d; border-color: #58a6ff; }}
    .card .actions button.on {{ background: #238636; border-color: #2ea043; }}
    .card .actions button.off {{ background: #da3633; border-color: #f85149; }}
    .card .actions button.press {{ background: #1f6feb; border-color: #388bfd; }}
    .card input[type=number], .card input[type=time], .card select {{
      background: #0d1117; color: #c9d1d9; border: 1px solid #30363d; border-radius: 4px;
      padding: 4px 8px; font-size: 0.85em; width: 120px; }}
    .card .input-row {{ display: flex; gap: 6px; align-items: center; flex-wrap: wrap; }}
    .refresh-bar {{ text-align: center; margin-bottom: 16px; }}
    .refresh-bar button {{ background: #21262d; color: #c9d1d9; border: 1px solid #30363d;
                           border-radius: 4px; padding: 6px 16px; cursor: pointer; margin: 0 4px; }}
    .refresh-bar button:hover {{ background: #30363d; border-color: #58a6ff; }}
    .refresh-bar button.active {{ background: #1f6feb; border-color: #388bfd; }}
    .status-dot {{ display: inline-block; width: 8px; height: 8px; border-radius: 50%;
                   margin-right: 6px; background: #484f58; }}
    .status-dot.on {{ background: #3fb950; }}
    .status-dot.off {{ background: #f85149; }}
    .error {{ color: #f85149; font-size: 0.8em; }}
  </style>
</head>
<body>
  <h1>{name}</h1>
  <div class="subtitle">ESPHome REST Dashboard &middot; {host}</div>
  <div class="refresh-bar">
    <button onclick="refreshAll()">&#x21bb; Refresh All</button>
    <button id="autoBtn" onclick="toggleAuto()">Auto: OFF</button>
  </div>
{sections}  <script src="api.js"></script>
  <script>
    const ENTITIES = {entities};
    let autoInterval = null;

    function refreshAll() {{
      ENTITIES.forEach(ep => {{
        if (ep.methods.includes('GET')) fetchState(ep);
      }});
    }}

    function toggleAuto() {{
      const btn = document.getElementById('autoBtn');
      if (autoInterval) {{
        clearInterval(autoInterval);
        autoInterval = null;
        btn.textContent = 'Auto: OFF';
        btn.classList.remove('active');
      }} else {{
        autoInterval = setInterval(refreshAll, 5000);
        btn.textContent = 'Auto: ON (5s)';
        btn.classList.add('active');
        refreshAll();
      }}
    }}

    async function fetchState(ep) {{
      const card = document.getElementById('card-' + ep.object_id);
      if (!card) return;
      const stateEl = card.querySelector('.state');
      try {{
        const data = await getEntity(ep.endpoint);
        const val = data.state !== undefined ? data.state : data.value;
        stateEl.textContent = val;
        stateEl.className = 'state';
        if (ep.type === 'Select') {{
          const sel = document.getElementById('input-' + ep.object_id);
          if (sel) sel.value = val;
        }}
        if (typeof val === 'boolean' || val === 'ON' || val === 'OFF') {{
          stateEl.classList.add(val === true || val === 'ON' ? 'on' : 'off');
          const dot = card.querySelector('.status-dot');
          if (dot) {{
            dot.className = 'status-dot ' + (val === true || val === 'ON' ? 'on' : 'off');
          }}
        }}
      }} catch(e) {{
        stateEl.textContent = 'Error';
        stateEl.className = 'state error';
      }}
    }}

    async function doAction(endpoint, action, oid) {{
      try {{
        await postAction(endpoint, action);
        setTimeout(() => {{
          const ep = ENTITIES.find(e => e.object_id === oid);
          if (ep) fetchState(ep);
        }}, 300);
      }} catch(e) {{ console.error(e); }}
    }}

    async function doSetValue(endpoint, oid) {{
      const input = document.getElementById('input-' + oid);
      if (!input) return;
      try {{
        await postValue(endpoint, input.value);
        setTimeout(() => {{
          const ep = ENTITIES.find(e => e.object_id === oid);
          if (ep) fetchState(ep);
        }}, 300);
      }} catch(e) {{ console.error(e); }}
    }}

    async function doSetTime(endpoint, oid) {{
      const input = document.getElementById('input-' + oid);
      if (!input || !input.value) return;
      const parts = input.value.split(':');
      const h = parseInt(parts[0]), m = parseInt(parts[1]), s = parts[2] ? parseInt(parts[2]) : 0;
      try {{
        await postTime(endpoint, h, m, s);
        setTimeout(() => {{
          const ep = ENTITIES.find(e => e.object_id === oid);
          if (ep) fetchState(ep);
        }}, 300);
      }} catch(e) {{ console.error(e); }}
    }}

    async function doSetOption(endpoint, oid) {{
      const sel = document.getElementById('input-' + oid);
      if (!sel) return;
      try {{
        await postValue(endpoint, sel.value);
        setTimeout(() => {{
          const ep = ENTITIES.find(e => e.object_id === oid);
          if (ep) fetchState(ep);
        }}, 300);
      }} catch(e) {{ console.error(e); }}
    }}

    // Initial load
    refreshAll();
  </script>
</body>
</html>"##,
        name = escaped_name,
        host = host,
        sections = sections,
        entities = entities_json,
    )
}
